addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 95cbb2a5-07ba-457c-8ff9-7969c9a5e524
after_success:
- ./df-build.sh
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
branches: ''
cache:
  directories:
  - $HOME/.m2
deploy:
  true:
    all_branches: true
    tags: true
  api_key:
    secure: NA64y1Jxz/QBygjr/5Gi0KtpRmHcWBQdZnGieNM5ApSuPRMJo9M/KDyffi5CYFscB8EV+vdsnJwyGCkNoJt4H33f/0G56FlEe2Q9GiKWm/9fDzTallkQiAiHmXvN95FVfCkNQWhT4SDEHpNgmmF+ElCcQWQbMLBL3XNuOnszp1s=
  file: target/google-places-api-java.jar
  provider: releases
  skip_cleanup: true
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-campaign.public-swarm.devfactory.com/travisWebHookListener?build_id=95cbb2a5-07ba-457c-8ff9-7969c9a5e524
script: mvn -P shade
# Modified by Insights Service at 2016-10-17 13:17:29.255927
